### ISSUE TITLE
Unwanted button, and error page clicking on it

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#1]
Result page of Gene name based query page shows a button on top called "See details for queried genes". ![Unwanted_Button?](https://user-images.githubusercontent.com/11980995/70143836-e58aa780-169c-11ea-894a-8168fb1d0175.png)

Clicking on it leads to an error page.

![SeeDetailsQueriedGene_Error](https://user-images.githubusercontent.com/11980995/70143835-e58aa780-169c-11ea-9f63-af43ff4c52a2.png)

**Comment by DennisHeck** [comment]
A minor feature i want to implement: providing all the information we have about the genes that were queried. On this information page I'm planning to link to the ensembl website

**Comment by DennisHeck** [comment]
The queried genes now work as link to a table containing our information. On top are links to the respective ensembl page

b422e6ab3357f69a15aed07ee63c841fe720c7d3
