### ISSUE TITLE
Region based search should format the geneID reporting in a better way

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#10]
![regionSearch_nocelltypeinfo](https://user-images.githubusercontent.com/11980995/70147640-f8a17580-16a4-11ea-9596-cac04072144d.png)
At the moment, it seems to display the whole gene table. Perhaps, its sufficient to show the geneID in the first field.

**Comment by DennisHeck** [comment]
Also solved when including new API functions
1be87de407338c45fd98704251675c32f8874a54
