### ISSUE TITLE
CREMs report the same REM entry 'n' times. n equals the number of REMs in the CREM

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#12]
REM Query Search: REM0236120

when clicking on the associated REM clusters, i see the below result. Each entry is displayed three times, as the CREM has 3 entries. 

<img width="1334" alt="Screenshot 2019-12-18 at 13 49 38" src="https://user-images.githubusercontent.com/11980995/71087893-8600c180-219d-11ea-9a39-efe2314b8d94.png">

**Comment by DennisHeck** [comment]
Fixed the clustering of the clusters

2d255a45ffe561f6c75970b15ae66a5438f4177a
