### ISSUE TITLE
File upload by default reports as REM not found in GeneQuery, REM Query

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#13]
There seems to be a problem with the upload a CSV option in both Gene/REM Query. From my understanding, it seems like the file is not being read at all.

<img width="879" alt="fileuploadNotworking" src="https://user-images.githubusercontent.com/11980995/71164615-bd2fab00-224f-11ea-90a0-5a08dabd571e.png">

The CSVs I used in the respective queries are below.

geneID_query.csv
-----------------
ENSG00000139874, 
ENSG00000274220

geneSymbol_query.csv
-----------------------
SSTR1,
DBR1,
FOXP3

remID_query.csv
-----------------
REM0595948,
REM0236120,
REM0236139

**Comment by skarunan** [comment]
This seems to be an issue only with Safari browser. 
In chrome browsers, as long as the cache is cleared the outputs are fine.

**Comment by skarunan** [comment]
This issue is not existing in Firefox under windows OS as well

**Comment by DennisHeck** [comment]
This is a problem specific to Safari. Safari does not seem to work with the way the upload file is received and processed. We recommend using any other Browser
