### ISSUE TITLE
Region query search using file upload reports a ValueError page

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#14]
The query file used:
region_query.csv
-----------------
chr4, 1000650, 420123,
chr2, 1369428, 3456742,

<img width="1059" alt="regionquery_error" src="https://user-images.githubusercontent.com/11980995/71165186-bc4b4900-2250-11ea-9c80-dff0bb11e660.png">

**Comment by DennisHeck** [comment]
Works now, tested with the same input as reported. Listing invalid inputs like a higher start than end position is being worked on.

4e79ee534f915e2d6f893ce47e914d0cc9f25442
