### ISSUE TITLE
using commas in CSV of region query doesn't work, but semicolon does

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#15]

**Comment by skarunan** [comment]
This seems to work fine in both firefox, and chrome in a Windows system. 
And the file gets processed, irrespective of whether I use comma (,) or semicolon (;)

**Comment by DennisHeck** [comment]
Corrected for a more reliable csv-readout

4e79ee534f915e2d6f893ce47e914d0cc9f25442
