### ISSUE TITLE
Gene Query search results in error page, when a wrong gene name is used in csv

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#17]
geneSymbol_query.csv: (same issue in chrome, and firefox)
SSTR1,
DBR1,
FOXP

FOXP does not exist in hg38.

The error page I get
![error_geneQuerysearch_unexistinggene](https://user-images.githubusercontent.com/11980995/71204133-ac0e8a80-229f-11ea-98b6-df1bcc9605f8.png)

**Comment by DennisHeck** [comment]
Now gives back an error message for the first invalid gene symbol found

c2e19ef010f4a2d00c49d26e35d396e920908240
