### ISSUE TITLE
Inconsistency in reporting CREMs

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#2]
The CREM IDs are being reported in different ways.

 - Search using GeneID tab reports as below
![GeneSearch_ClusterOfREMid](https://user-images.githubusercontent.com/11980995/70144150-9c872300-169d-11ea-96d9-117b6bfd5ed4.png)

- Clicking on this CREM doesn't report all the REMs contained in CREM. (use geneID: ENSG00000239906)

 - Whereas searching directly through REM reports as below.
![REMSearch_CREMs](https://user-images.githubusercontent.com/11980995/70144149-9c872300-169d-11ea-8574-9a7657ef1d67.png)

- The CREM link is not clickable

 - There is no CREM reported in GeneRegion based search.
![NoCREM_geneRegion](https://user-images.githubusercontent.com/11980995/70146838-52a13b80-16a3-11ea-81cb-0214e6c25fc9.png)

**Comment by DennisHeck** [comment]
This was only placeholder data. Should now work as planned with all links and be displayed consistently.

1be87de407338c45fd98704251675c32f8874a54
