### ISSUE TITLE
Better description of GeneID - validation tooltip, and Spelling

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#4]
![GeneID_ValidationToolTip](https://user-images.githubusercontent.com/11980995/70144671-b70dcc00-169e-11ea-8dd5-0baae677f849.png)

 - While the tool tip is useful, it is a bit confusing as the brackets says 10 digits. Perhaps, its better to say something like ENSG followed by 10 digits or so.

 - Also, the spelling should say "Ensembl" not ensemble.

**Comment by DennisHeck** [comment]
Fixed, as well as in the tooltip for the REMID query
