### ISSUE TITLE
Table display style of cell type based headers 

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#5]
The headers of activity, and sample number information doesn't match with the rest of the table.
![MismatchHeaders](https://user-images.githubusercontent.com/11980995/70145145-b6c20080-169f-11ea-9074-eba3696b2e23.png)

**Comment by DennisHeck** [comment]
Fixed some layout related aspects.
b422e6ab3357f69a15aed07ee63c841fe720c7d3
