### ISSUE TITLE
Filtering criteria for auto-fill

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#6]
What's the autofill filter criteria. Does it start searching after three or two characters? I thought you implemented starting with 3 characters, but I see results with two characters. Is this intentional?
![Autofill_FilterChar3or2](https://user-images.githubusercontent.com/11980995/70145403-48317280-16a0-11ea-8510-3f25b4eed6eb.png)

**Comment by DennisHeck** [comment]
It's intentional. For GeneSymbols it starts suggesting after three and for cellTypes after two characters.
