### ISSUE TITLE
No error handling for wrong input file in reqionQuery, geneQuery and REMQuery tabs

### ISSUE THREAD

**Issue by skarunan** [TeamRegio/EpiRegioDB#8]
![Screenshot 2019-12-04 at 14 36 11](https://user-images.githubusercontent.com/11980995/70146977-ad3a9780-16a3-11ea-92b4-ad885ba04fcb.png)

**Comment by DennisHeck** [comment]
Only csv is possible per drag and drop now. If the input file does contain invalid inputs, the error page will be displayed, showing the details of the query and hints on the kind of error.

b422e6ab3357f69a15aed07ee63c841fe720c7d3
